
export interface User {
  id: string;
  name: string;
  email?: string;
}

export interface Message {
  id: string;
  text: string;
  sender: 'user' | 'bot' | 'expert';
  timestamp: number;
  avatar?: string;
}

export interface TestQuestion {
  id: string;
  text: string;
  options: { id: string; text: string }[];
  correctOptionId?: string; // For scoring, if applicable
  points?: number; // Points for this answer
}

export interface TestResult {
  score: number;
  maxScore: number;
  percentage: number;
  feedback: string;
  advice?: string; // Could be generated by AI
}

export interface Expert {
  id: string;
  name: string;
  specialty: string;
  phone: string;
  email: string;
  avatarUrl: string;
}

export enum Page {
  Home = '/home',
  Login = '/login',
  Register = '/register',
  AskMe = '/ask-me',
  Test = '/test',
  TestQuiz = '/test/quiz',
  TestResults = '/test/results',
  ContactExpert = '/contact-expert',
}
